apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
images:
  - name: AUTHOR/IMAGE_WRITE
    newName: dxvann/log-output-write
    newTag: "1.11"
  - name: AUTHOR/IMAGE_READ
    newName: dxvann/log-output-read
    newTag: "2.5"
