name: Remove Namespace on Branch Deletion
on: delete

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: asia-south1-a

jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: gcloud info

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Evaluate namespace from branch name
        run: echo "NAMESPACE=$([[ "$BRANCH" == "main" ]] && echo "project" || echo "$BRANCH")" >> $GITHUB_ENV

      - name: Delete the namespace
        run: kubectl delete namespace $NAMESPACE

      - name: Verify namespace deletion
        run: |-
            kubectl get namespaces
            kubectl describe namespace $NAMESPACE || echo "Namespace $NAMESPACE successfully deleted"
            kubectl get all -n $NAMESPACE || echo "All resources in namespace $NAMESPACE successfully deleted"
